[workspace.package]

[workspace]
members = [
    "piggylike",
    "engine",
    "engine/crates/smart_camera",
    "engine/crates/tilemap",
    "engine/crates/metadata",
    "engine/crates/editor"
]

resolver = "2" 

[workspace.dependencies]
bevy = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.82"
bevy_egui = "0.15.0"