[workspace.package]

[workspace]
members = [
    "piggylike",
    "engine",
    "engine/crates/smart_camera",
    "engine/crates/tilemap",
    "engine/crates/metadata",
    "engine/crates/editor",
    "engine/crates/map"
]

resolver = "2" 

[workspace.dependencies]
bevy = "0.8"
serde = { version = "1.0", features = ["derive"] }
ndarray = { version = "0.15.6", features = ["serde"] }
serde_json = "1.0.82"
bevy_egui = "0.15.0"
tilemap = { path = "engine/crates/tilemap" }
metadata = { path = "engine/crates/metadata" }
smart_camera = { path = "engine/crates/smart_camera" }
map = { path = "engine/crates/map" }
rand = "0.8.5"