[package]
name = "engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.3.23"
macroquad-tiled = "0.1.1"
rhai = "1.8.0"
notify = "4.0.17"
generational-arena = "0.2.8"
parry2d = "0.9.0"